//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IVS.rc
//
#define ID_SCROLLUP                     2
#define ID_SCROLLUP2                    3
#define ID_SCROLLDN                     3
#define ID_UPDATE                       3
#define ID_SAVE_TXT                     4
#define ID_CHANGE_LOG                   5
#define ID_LOAD_LOG                     5
#define IDD_ABOUTBOX                    100
#define IDS_CAMERA                      105
#define IDB_LOGO_BIG                    114
#define IDR_MAINFRAME                   128
#define IDS_PROCESS_IMAGE               129
#define IDS_LOAD_IMAGE                  130
#define IDD_INFO_WINDOW                 131
#define IDS_TEST                        132
#define IDD_INPUT_FIGURES               133
#define IDS_THREAD_ONOFF                134
#define IDD_RECIPE_DIALOG               140
#define IDD_INPUT_STRING                145
#define ARROW_UP                        146
#define IDD_INPUT_LETTERS               147
#define IDD_CFR21_DIALOG                150
#define IDD_CFR21_SHOW                  151
#define IDD_DIALOG1                     153
#define IDD_INFO_BOX                    154
#define IDD_CFR21_NEW                   155
#define IDB_ARROW_DOWN                  159
#define IDD_CONTAINER                   160
#define IDB_ARROW_LEFT                  161
#define IDD_SPIN_DIALOG                 162
#define IDD_AREA_DIALOG                 163
#define IDB_ARROW_UP                    163
#define IDD_CAROUSEL_HEIGHT             164
#define IDD_HEIGHT_DIALOG               164
#define IDB_ARROW_RIGHT                 165
#define IDD_SPIN_DIALOG1                165
#define IDD_GRAPHICS_DIALOG             165
#define IDB_HOR_ENLARGE                 166
#define IDB_HOR_REDUCE                  167
#define IDB_VER_ENLARGE                 168
#define IDB_VER_REDUCE                  171
#define IDD_DIALOG2                     172
#define IDB_BITMAP1                     173
#define IDI_ICON1                       177
#define IDB_BITMAP2                     178
#define IDB_BITMAP3                     180
#define IDB_BITMAP5                     182
#define IDB_SPLASH                      182
#define IDD_JOGWND                      183
#define IDB_VISIQUICK_LOGO              186
#define IDB_BITMAP4                     190
#define IDB_LOGO_SMALL                  190
#define IDD_BATCH_DIALOG                194
#define IDD_LOG_VIEWER                  196
#define IDD_USERS_MNGR                  197
#define IDC_TEXT_1                      1000
#define IDC_TEXT_2                      1001
#define IDC_CURRENT_VAL                 1004
#define IDC_CURRENT_VAL2                1005
#define IDC_CURRENT_DESC                1005
#define IDC_BUTTON_DOT                  1010
#define IDC_BUTTON_CHNGSGN              1011
#define ID_LOAD_RECIPE                  1014
#define ID_SAVE_RECIPE                  1015
#define ID_SCROLL_UP                    1016
#define ID_SCROLL_DOWN                  1017
#define ID_RENAME_RECIPE                1018
#define ID_DELETE_RECIPE                1019
#define ID_CLOSE_RECIPE                 1020
#define ID_SEND_DATA                    1021
#define ID_CLOSE                        1022
#define ID_CANCEL                       1023
#define ID_INDEX                        1027
#define IDC_CURRENT                     1028
#define ID_HEIGHT_ADJUST                1029
#define IDC_SPIN1                       1030
#define IDC_SPIN3                       1032
#define IDC_SPIN_TEXT                   1034
#define IDC_RADIO1                      1043
#define IDC_RICHEDIT21                  1045
#define ID_X10                          1047
#define IDC_AXIS_TEXT                   1048
#define IDC_AXIS                        1050
#define IDC_EDIT1                       1050
#define IDC_EDIT_LV                     1050
#define IDC_JOGPLUS                     1051
#define IDC_JOGMINUS                    1052
#define IDC_HOMING                      1053
#define IDC_STOP                        1054
#define IDC_USER_SELECT                 1059
#define ID_MOVE_UP                      1060
#define ID_ADD                          1060
#define ID_MOVE_DOWN                    1061
#define ID_DELETE                       1061
#define ID_MOVE_LEFT                    1062
#define IDC_INDEX                       1062
#define ID_MOVE_RIGHT                   1063
#define IDC_TXTUSERNAME                 1063
#define ID_HOR_REDUCE                   1064
#define IDC_TXTPASSWORD                 1064
#define ID_HOR_ENLARGE                  1065
#define IDC_TXTUSERNAME2                1065
#define ID_VER_REDUCE                   1066
#define IDC_TXTUSERNAME3                1066
#define ID_VER_ENLARGE                  1067
#define IDC_TXTUSERNAME4                1067
#define IDC_SUPERVISOR                  1068
#define IDC_MAINTENANCE                 1069
#define IDC_CAPTION_TXT                 1070
#define IDC_OPERATOR                    1070
#define IDC_BATCHOPER_TXT               1071
#define IDC_NOLEVEL                     1071
#define IDC_BATCHOPER_VAL               1072
#define IDC_BATCHCODE_TXT               1073
#define IDC_USERNAME                    1073
#define IDC_BATCHCODE_VAL               1074
#define IDC_PASSWORD                    1074
#define IDC_BATCHNAME_TXT               1075
#define IDC_BATCHNAME_VAL               1076
#define IDC_BATCHDESC_TXT               1077
#define IDC_BATCHDESC_VAL               1078
#define IDD_CALIBRATION                 1100
#define IDC_CALIB_DESC0                 1110
#define IDC_CALIB_DESC1                 1111
#define IDC_CALIB_DESC2                 1112
#define IDC_CALIB_DESC3                 1113
#define IDC_CALIB_DESC4                 1114
#define IDC_CALIB_DESC5                 1115
#define IDC_CALIB_DESC6                 1116
#define IDC_CALIB_DESC7                 1117
#define IDC_CALIB_DESC8                 1118
#define IDC_CALIB_DESC9                 1119
#define IDC_CALIB_G0A                   1120
#define IDC_CALIB_G1A                   1121
#define IDC_CALIB_G2A                   1122
#define IDC_CALIB_G3A                   1123
#define IDC_CALIB_G4A                   1124
#define IDC_CALIB_G5A                   1125
#define IDC_CALIB_G6A                   1126
#define IDC_CALIB_G7A                   1127
#define IDC_CALIB_G8A                   1128
#define IDC_CALIB_G9A                   1129
#define IDC_CALIB_G0B                   1130
#define IDC_CALIB_G1B                   1131
#define IDC_CALIB_G2B                   1132
#define IDC_CALIB_G3B                   1133
#define IDC_CALIB_G4B                   1134
#define IDC_CALIB_G5B                   1135
#define IDC_CALIB_G6B                   1136
#define IDC_CALIB_G7B                   1137
#define IDC_CALIB_G8B                   1138
#define IDC_CALIB_G9B                   1139
#define IDC_CALIB_G0D                   1140
#define IDC_CALIB_G1D                   1141
#define IDC_CALIB_G2D                   1142
#define IDC_CALIB_G3D                   1143
#define IDC_CALIB_G4D                   1144
#define IDC_CALIB_G5D                   1145
#define IDC_CALIB_G6D                   1146
#define IDC_CALIB_G7D                   1147
#define IDC_CALIB_G8D                   1148
#define IDC_CALIB_G9D                   1149
#define IDC_BACKSPACE                   2028
#define IDC_CLEAR                       2030
#define IDC_BUTTON_SPC                  2032
#define IDC_BUTTON_0                    2048
#define IDC_BUTTON_1                    2049
#define IDC_BUTTON_2                    2050
#define IDC_BUTTON_3                    2051
#define IDC_BUTTON_4                    2052
#define IDC_BUTTON_5                    2053
#define IDC_BUTTON_6                    2054
#define IDC_BUTTON_7                    2055
#define IDC_BUTTON_8                    2056
#define IDC_BUTTON_9                    2057
#define IDC_BUTTON_A                    2065
#define IDC_BUTTON_B                    2066
#define IDC_BUTTON_C                    2067
#define IDC_BUTTON_D                    2068
#define IDC_BUTTON_E                    2069
#define IDC_BUTTON_F                    2070
#define IDC_BUTTON_G                    2071
#define IDC_BUTTON_H                    2072
#define IDC_BUTTON_I                    2073
#define IDC_BUTTON_J                    2074
#define IDC_BUTTON_K                    2075
#define IDC_BUTTON_L                    2076
#define IDC_BUTTON_M                    2077
#define IDC_BUTTON_N                    2078
#define IDC_BUTTON_O                    2079
#define IDC_BUTTON_P                    2080
#define IDC_BUTTON_Q                    2081
#define IDC_BUTTON_R                    2082
#define IDC_BUTTON_S                    2083
#define IDC_BUTTON_T                    2084
#define IDC_BUTTON_U                    2085
#define IDC_BUTTON_V                    2086
#define IDC_BUTTON_W                    2087
#define IDC_BUTTON_X                    2088
#define IDC_BUTTON_Y                    2089
#define IDC_BUTTON_Z                    2090
#define IDC_BUTTON_UPLOW                2091
#define ID_LOGIN_ENTRY                  2100
#define ID_LOGIN_EXIT                   2101
#define ID_LOGIN_MODIFY                 2102
#define ID_LOGIN_DELETE                 2103
#define ID_EXPORT_LOG                   2104
#define ID_LOGIN_LOGOUT                 2105
#define ID_EXTRA_THREADRUNNING          32775
#define ID_EXTRA_CAMERA                 32777
#define IDS_SAVE_PARAMS                 32778
#define IDS_LOAD_PARAMS                 32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
